// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Diet struct {
	ID    int32
	Meal  pgtype.Text
	Date  pgtype.Date
	Items []string
	Notes pgtype.Text
}

type Menstrual struct {
	ID          int32
	PeriodEvent pgtype.Text
	Date        pgtype.Date
	FlowLevel   pgtype.Text
	Notes       pgtype.Text
}

type Sleep struct {
	ID          int32
	Date        pgtype.Date
	Duration    pgtype.Float8
	Quality     pgtype.Int4
	Disruptions pgtype.Text
	Notes       pgtype.Text
}

type Symptom struct {
	ID      int32
	Date    pgtype.Date
	Nausea  pgtype.Int4
	Fatigue pgtype.Int4
	Pain    pgtype.Int4
	Notes   pgtype.Text
}
