// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Diet struct {
	ID    int32
	Meal  pgtype.Text
	Items []string
	Time  pgtype.Timestamp
}

type Menstrual struct {
	ID          int32
	CycleDay    pgtype.Int4
	PainRating  pgtype.Int4
	StressLevel pgtype.Int4
	Medication  []string
}

type Sleep struct {
	ID            int32
	Duration      pgtype.Float8
	Efficiency    pgtype.Int4
	DeepPct       pgtype.Int4
	Latency       pgtype.Int4
	NumAwakenings pgtype.Int4
}
